### ISSUE TITLE
subset matches for arrays of objects don't properly error

### ISSUE THREAD

**Issue by mjhm** [mjhm/lodash-match-pattern#34]
```
matchPattern([{a: 'ab'}], '[{a: "ab"} ...]')
```
Results in error string
```
'Array [ { a: \'ab\' } ] isn\'t a subset match of Array [ { a: \'ab\' } ]'
```
This should either be allowed or a more instructive error message.

**Comment by snowyu** [comment]
this bug confirmed. 
 
```js
matchPattern([{}, 1], [{},'...'])

   'Array [ {}, 1 ] isn\'t a subset match of Array [ {} ]'
```

It should treat the array as object to match.

**Comment by mjhm** [comment]
@snowyu Thanks -- I'm going to have to fix this.

**Comment by mjhm** [comment]
Fixed https://github.com/Originate/lodash-match-pattern/releases/tag/v1.3.1

This now does deep matching of explicit subset, superset, equalset values, though it still doesn't allow matching functions in set elements.  Such corner cases are probably too complicated to be implemented in this library.

**Comment by Sarilha** [comment]
I've solved my problem by getting every object at the set and using "matching functions" to compare every object.

Like the function below:
`function successArray(res, status, objectToCompare) {
  chai.expect(res)
    .to.have.status(status);
  chai.expect(res.body)
    .is.an('array');
  res.body.forEach(function(entry) {
    chai.expect(entry).to.matchPattern(objectToCompare);
  });
 `
